# FSDP related settings
generator_fsdp_wrap_strategy: transformer
real_score_fsdp_wrap_strategy: transformer
fake_score_fsdp_wrap_strategy: transformer
text_encoder_fsdp_wrap_strategy: size
sharding_strategy: full # TODO: full or hybrid_full

# Logging
wandb_host: https://api.wandb.ai
wandb_key: afa4e78959b05201e369f448504697737237fc5c
wandb_entity: shukai_gong
wandb_project: ovi-self-forcing
# wandb_name: wan_causal_dmd # TODO: do we need this?

# Model settings
real_name: Ovi                  # teacher model, frozen
fake_name: Ovi                  # critic model, trainable
generator_name: Ovi             # student model, trainable
generator_type: causal   # bidirectional diffusion, not causal diffusion
real_path: /cpfs01/gongshukai/weights/Ovi/Ovi/model.safetensors
fake_path: /cpfs01/gongshukai/weights/Ovi/Ovi/model.safetensors
generator_ckpt: /cpfs01/gongshukai/step_distillation/logs/ovi_ode_init/checkpoint_model_019000/model.pt

## Ovi Self Forcing Distillation settings
distribution_loss: dmd            
trainer: score_distillation_ovi   
num_blocks: 8
num_training_frames_video: 32
num_training_frames_audio: 160
vid_block_size: 4
aud_block_size: 20
start_gradient_frame_index_video: 0
context_noise: 0.0
last_step_only: false
same_step_accross_blocks: false
# NOTE: for causal
video_latent_shape: [32, 48, 44, 80]
audio_latent_shape: [160, 20]

# # NOTE: for bidirectional
# video_latent_shape: [31, 48, 44, 80]
# audio_latent_shape: [157, 20]

load_raw_video: false
model_kwargs:
  timestep_shift: 5.0
initial_step: 0
dfake_gen_update_ratio: 5
denoising_step_list: [1000, 750, 500, 250]
num_train_timestep: 1000
timestep_shift: 5.0
video_guidance_scale: 2.0 # ADDED: Specific guidance for video teacher
audio_guidance_scale: 1.5 # ADDED: Specific guidance for audio teacher
denoising_loss_type: x0 # TODO: x0 or flow?
video_negative_prompt: "jitter, bad hands, blur, distortion"  # Artifacts to avoid in video
audio_negative_prompt: "robotic, muffled, echo, distorted"    # Artifacts to avoid in audio


## Training settings
text_encoder_cpu_offload: true
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true, 将离散步数映射到连续时间步
ts_schedule: false
gradient_checkpointing: true
mixed_precision: true
seed: 0
lr: 2.0e-06             # orginal lr: 5e-7
lr_critic: 4.0e-07      # orginal lr_critic: 1e-7
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
batch_size: 2 # changing to batch size 1, since the thing is quite large
ema_weight: 0.99
ema_start_step: 200
total_batch_size: 64

# checkpointing
log_iters: 2000
checkpoints_to_keep: [6000, ]
num_keep_checkpoints: 2
video_log_iters: 300

## Dataset settings
data_path: data/ovi_dataset_part2.csv
num_frames: 121
h: 704
w: 1280
audio_sample_rate: 16000
audio_duration_secs: 5