# FSDP related settings
generator_fsdp_wrap_strategy: transformer
text_encoder_fsdp_wrap_strategy: size
sharding_strategy: hybrid_full

# Logging
wandb_host: https://api.wandb.ai
wandb_key: afa4e78959b05201e369f448504697737237fc5c
wandb_entity: shukai_gong-renmin-university-of-china
wandb_project: ode_pretrain
wandb_name: ovi_causal_ode_pretrain

## Model settings
model_name: Ovi
generator_name: Ovi
generator_type: causal
generator_path: /cpfs01/gongshukai/weights/Ovi/Ovi/model.safetensors

## ODE pretraining settings
# generator_ckpt: (Optional) Path to resume from, e.g. previous ode checkpoint
distribution_loss: ode
trainer: ovi_ode # <--- 新增的 Trainer 类型
denoising_step_list: [1000, 750, 500, 250]
timestep_shift: 5.0

# Ovi specific model kwargs

model_kwargs:
  video_config_path: "ovi/configs/model/dit/video.json"
  audio_config_path: "ovi/configs/model/dit/audio.json"
  timestep_shift: 5.0

## Training settings
gradient_checkpointing: true
mixed_precision: true  # 使用 bf16
warp_denoising_step: true
data_path: /cpfs01/gongshukai/step_distillation/data/ode_pairs_1219
batch_size: 4
max_pair: 10000000
# lr: 2.0e-06
lr: 1.0e-5
beta1: 0.9
beta2: 0.999
weight_decay: 0.01
log_iters: 1000
no_visualize: true
load_raw_video: false
seed: 0